"""Add student detailed info columns

Revision ID: d53f058fae54
Revises: 
Create Date: 2025-09-02 03:33:54.946009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53f058fae54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('fathers_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('student_class', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contact_number')
        batch_op.drop_column('student_class')
        batch_op.drop_column('address')
        batch_op.drop_column('fathers_name')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
